name: Node.js CI
on: [push]
jobs:
  Build And Test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.15.4'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm run test:all -- --reporter xunit --reporter-option output=tests/testSuite.xml
    - name: Archive Test Suite Results
      uses: actions/upload-artifact@v2
      with:
        name: test suite
        path: tests/testSuite.xml
    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action@v1.9
      if: always()
      with:
        files: tests/testSuite.xml
